apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  labels:
    service: ml-app
spec:
  selector:
    app: ml-app
  ports: # route external requests coming in on port 5000 to our pod
  - port: 5000 #entry port for external requests
    targetPort: 5000 #target port on any pods named ml-app
  type: LoadBalancer