apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app-container
        image: bhavenp/sentiment-analysis:latest
        imagePullPolicy: Always
        command: ['/bin/bash'] #starts up the Flask application
        args: ['ml_deploy_demo/run.sh']
        ports:
        - containerPort: 5000
