apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  labels:
    service: ml-app
spec:
  selector:
    app: ml-app
  ports:
  - port: 5000 #entry port for 
    targetPort: 5000 #target port on any pods named server-app
  type: LoadBalancer