# insert data related stuff

train:
    experiment:
        output_dirname: "/app/experiment_output"

    data:
        dataset_name: "imdb"
        # train dataset path
        # dataset_path:

    model:
        name: "sentiment_dnn"
        params: {
            "hidden_units": 16,
            "hidden_layers": 1,
        }
    logging:
        config_path: "/app/logging.yaml"

predict:
    data:
        # validation dataset path
        # dataset_path:
    model:
        dirname: "/app/models/sentiment"
        version: "1"

    logging:
        config_path: "/app/logging.yaml"
